CREATE DATABASE IF NOT EXISTS erzacell CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE erzacell;

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(50) NOT NULL,
  product VARCHAR(255) NOT NULL,
  amount BIGINT NOT NULL,
  target VARCHAR(100) NOT NULL,
  payment_method VARCHAR(50) NOT NULL,
  wallet VARCHAR(50) DEFAULT NULL,
  bank_amount BIGINT DEFAULT NULL,
  bank_name VARCHAR(100) DEFAULT NULL,
  note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
